name: shule_direct_chat_app
description: "Shule Direct Chat App - A Flutter-based real-time messaging application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  dio: ^5.9.1
  flutter_secure_storage: ^10.0.0
  web_socket_channel: ^3.0.3
  intl: ^0.20.2
  google_fonts: ^6.3.2
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/app_icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon/app.png
  remove_alpha_ios: true
